version: '3.8'
services:

  # RPC daemon
  bitcoin:
    image: ghcr.io/vulpemventures/bitcoin:latest
    user: 1000:1000
    container_name: bitcoin
    command:
      - -datadir=config
    ports:
      - 18443:18443
      - 18444:18444
      # ZMQ
      - 28332:28332
      - 28333:28333
    volumes:
      - ./volumes/bitcoin/:/config
    restart: unless-stopped

  liquid:
    image: ghcr.io/vulpemventures/elements:latest
    user: 1000:1000
    container_name: liquid
    command:
      - -datadir=config
    ports:
      - 18884:18884
      - 18886:18886
      # ZMQ
      - 38332:38332
      - 38333:38333
    volumes:
      - ./volumes/elements/:/config
    restart: unless-stopped

  lnd:
    container_name: lnd
    image: lightninglabs/lnd:v0.14.3-beta
    user: 1000:1000
    depends_on:
      - bitcoin
    volumes:
      - ./volumes/lnd:/data/.lnd
    environment:
      HOME: /data
    restart: unless-stopped
    stop_grace_period: 5m30s
    ports:
      - "9735:9735" # p2p
      - "10009:10009" # grpc

  peerswap:
    container_name: peerswap
    image: ghcr.io/vulpemventures/peerswap:latest
    depends_on:
      - bitcoin
      - liquid
      - lnd
    ports:
      - 42069:42069
    restart: unless-stopped
    volumes:
      - ./volumes/peerswap:/home/peerswap/.peerswap
      - ./volumes/lnd:/home/peerswap/.lnd
  
networks:
  default:
    name: peerswap_box
