version: '3.8'
services:

  # RPC daemon
  bitcoin:
    image: ghcr.io/vulpemventures/bitcoin:latest
    user: 1000:1000
    container_name: bitcoin
    command:
      - -datadir=config
    ports:
      - 18443:18443
      - 18444:18444
      # ZMQ
      - 28332:28332
      - 28333:28333
    volumes:
      - ./volumes/bitcoin/:/config
    restart: unless-stopped

  liquid:
    image: ghcr.io/vulpemventures/elements:latest
    user: 1000:1000
    container_name: liquid
    command:
      - -datadir=config
    ports:
      - 18884:18884
      - 18886:18886
      # ZMQ
      - 38332:38332
      - 38333:38333
    volumes:
      - ./volumes/elements/:/config
    restart: unless-stopped


  cln:
    container_name: cln
    image: elementsproject/lightningd:latest
    environment:
      LIGHTNINGD_PORT: 9935
      EXPOSE_TCP: "true"
    command: 
      - --network=regtest 
      - --alias=nigiri
      - --bitcoin-rpcconnect=bitcoin:18443
      - --bitcoin-rpcuser=admin1 
      - --bitcoin-rpcpassword=123 
      - --log-level=debug 
      - --plugin=/root/.lightning/plugins/peerswap-plugin
      - --log-level=debug:plugin-peerswap-plugin
      - --peerswap-bitcoin-rpchost=bitcoin ## Host of bitcoind rpc (default: localhost)
      - --peerswap-bitcoin-rpcport=18443 ## Port of bitcoind rpc (default: network-default)
      - --peerswap-bitcoin-rpcuser=admin1 ## User for bitcoind rpc
      - --peerswap-bitcoin-rpcpassword=123 ## Password for bitcoind rpc
      - --peerswap-elementsd-enabled ## Override liquid enable (default: true)
      - --peerswap-elementsd-rpchost=liquid ## Host of elementsd rpc (default: localhost)
      - --peerswap-elementsd-rpcport=18884 ## Port of elementsd rpc (default: 18888)
      - --peerswap-elementsd-rpcuser=admin1 ## User for elementsd rpc
      - --peerswap-elementsd-rpcpassword=123 ## Password for elementsd rpc
      - --peerswap-elementsd-rpcwallet=""
    depends_on:
      - bitcoin
    ports:
      - 9935:9935 # p2p
      - 9835:9835 # rpc
    restart: unless-stopped
    volumes:
      - ./volumes/lightningd:/root/.lightning
      - ./volumes/bitcoin:/etc/bitcoin
  

  lnd:
    container_name: lnd
    image: lightninglabs/lnd:v0.14.3-beta
    user: 1000:1000
    depends_on:
      - bitcoin
    volumes:
      - ./volumes/lnd:/data/.lnd
    environment:
      HOME: /data
    restart: unless-stopped
    stop_grace_period: 5m30s
    ports:
      - "9735:9735" # p2p
      - "10009:10009" # grpc

  peerswap:
    container_name: peerswap
    image: ghcr.io/vulpemventures/peerswap:latest
    depends_on:
      - bitcoin
      - liquid
      - lnd
    ports:
      - 42069:42069
    restart: unless-stopped
    volumes:
      - ./volumes/peerswap:/home/peerswap/.peerswap
      - ./volumes/lnd:/home/peerswap/.lnd

networks:
  default:
    name: peerswap_box
